spring:
  datasource:
   username: root
   password: 123456
   url: jdbc:mysql://localhost:3306/mail?serverTimeZone=UTC&useUnicode=true&characterEncoding=utf-8
   driver-class-name: com.mysql.jdbc.Driver

#与mybatis相关
mybatis:
  type-aliases-package: com.woomq.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
  #驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true
